### PR TITLE
Resolve issues with symlinks on Linux and Windows machines

### LINKED ISSUE #146: postinstall does not run as expected on ubuntu
The `postinstall` script basically creates the symlinks:
android -> lib/android
ios -> lib/ios

This is the result of running it in OSX: 

osx-works

This is the result of running it in Ubuntu:

unbunto-problem

Trying to navigate in Ubuntu to `ios` or `android` library will not work.
<br>
It's important to mention that running `ln -sf lib/{ios,android} .` directly will work as expected:

ubuntu-work

### PR DESCRIPTION
**Pull request by chrismllr**
Resolves #146 

Instead of using an alternate symlinking method, restructure the project so the symlinks are unnecessary. This involves moving all files within `lib` top level, and removing `lib`.

I understand this may be a heavy-handed solution, I am open to critiques and other solutions. This seemed the simplest way to solve the problem, albeit causing a lot of file changes.

### CODE REVIEW

**Comment by hoboman313** [comment]
I would advise against merging this. Sure it may work on your OS (linux), but it still breaks on windows. The correct solution to this postinstall problem should work on all platforms.

**Comment by chrismllr** [comment]
@hoboman313 I've updated to the suggested fs method. Given that any user installing this lib will need to have node, I believe this solves for the broader use case?

**Comment by chrismllr** [comment]
Scratch it, still trying. There seems to be an issue creating symlink when the files already exist: https://stackoverflow.com/questions/29819963/how-to-force-a-symlink-creation-by-overriding-the-existing-symlink

**Comment by chrismllr** [comment]
This library solves the issue, but it would require adding a dev-dependency to the lib:
https://github.com/IonicaBizau/node-lnf

**Comment by chrismllr** [comment]
Refer to #175 for new solution

**Comment by chrismllr** [comment]
Extra PR was mistakenly created. Keeping this open to continue discussion.

**Comment by chrismllr** [comment]
@hoboman313 Can you test on windows machine? I've updated the description and altered the solution.

**Comment by salah-ghanim** [comment]
what's the status here ?

**Comment by DylanVann** [comment]
I didn't see this PR before creating another one. Does roughly the same thing. Although this PR is missing some references to the previous structure in the examples and it needs conflicts resolved.

https://github.com/wix/react-native-interactable/pull/211

**Comment by chrismllr** [comment]
@DylanVann Yep. Yours tackles the same issues, and is up to date. I am comfortable closing this PR in favor of #211

**Pull request closed without merging**
