### PR TITLE
Add onSnapStart event

### PR DESCRIPTION
**Pull request by gabeboning**
This adds an event that triggers when gesture ends and snap behavior starts. 

Addresses the request in #70, and might be useful for #107.

### CODE REVIEW

**Comment by Anu2g** [comment]
💯

**Comment by seb0zz** [comment]
Would be awesome if this could be merged, works like a charm

**Comment by jstheoriginal** [comment]
Would like to see this merged in as well. 🙏

**Comment by Anu2g** [comment]
Now that the Android code has been added, any hesitations on merging this?

**Comment by touqeerkhan11** [comment]
Hey! onSnapStart is NOT triggering when snapping programmatically using the instance.snapTo method. Can we fix this to be able to merge?

**Comment by kyle-ssg** [comment]
Using this over wix's for now, this could really do with merging!

**Comment by maxs15** [comment]
@rotemmiz Any reason this PR not getting merged ?

**Comment by bbil** [comment]
+1 to this. Looks like this event is exactly what I'm looking for right now.

**Comment by alexichristakis** [comment]
+1, can this be merged soon?

**Comment by woodpav** [comment]
Can we get a merge?

**Comment by bbil** [comment]
Woohoo! Glad to see a bunch of merges in this project. Now to see if I can remove my hacky solution...

**Pull request merged**
