### PR TITLE
fix(ios): make it possible to install via CocoaPods

### PR DESCRIPTION
**Pull request by sondremare**
The podspec file was npm ignored, resulting in linking via CocaPods did not work

### CODE REVIEW

**Comment by rgoldiez** [comment]
Why would this not be merged?

**Comment by DaBs** [comment]
This is critical to merge for React Native 0.60 :)

**Comment by congnguyen91** [comment]
+ 1

**Comment by congnguyen91** [comment]
+1

**Comment by ahanriat** [comment]
@sondremare Friendly ping 🤗

**Comment by ahanriat** [comment]
@Inbal-Tish Friendly ping 🤗

**Comment by ammichael** [comment]
@Inbal-Tish could you please give a look at this PR? this is *crucial* to anyone upgrading to RN 0.60. thanks a lot!

**Comment by alexichristakis** [comment]
I've just installed from master in the interim to include the podspec

**Comment by mtzfactory** [comment]
Yeah, that's crucial!

**Comment by brandons** [comment]
Bumping this. @Inbal-Tish Can we get this approved?

**Comment by keithhackbarth** [comment]
BUMP!!!!!

**Comment by darran-kelinske-fivestars** [comment]
bump again <3

**Comment by ammichael** [comment]
Is this repo dead? This PR was opened 7 months ago and it changes 3 lines. Seriously no one can test and approve it? It clearly has nothing to do with Android build.

**Comment by rotemmiz** [comment]
Redone in #300 - Original PR had some git reference messup (detached head, unreachable by CI, caused this PR build to fail).
I am closing this PR in favour of #300. Thanks for your contribution @sondremare, we'll make sure this is merged and published ASAP.

**Pull request closed without merging**
